[package]
name = "forkserver_libafl_cc"
version = "0.13.2"
authors = ["ergrelet <ergrelet@users.noreply.github.com>"]
edition = "2021"

[features]
default = ["std"]
std = []
# Forces a crash
crash = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
which = { version = "6.0" }

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nix = { version = "0.29", features = ["signal"] }
libafl = { path = "../../../libafl/" }
libafl_bolts = { path = "../../../libafl_bolts/" }
libafl_cc = { path = "../../../libafl_cc/" }
libafl_targets = { path = "../../../libafl_targets/", features = [
  "sancov_pcguard_hitcounts",
  "libfuzzer",
  "pointer_maps",
] }
env_logger = "0.11"

[lib]
name = "libforkserver_libafl_cc"
crate-type = ["staticlib"]
