# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: scripts/fmt_all.sh check
        language: script
      - id: taplo
        name: taplo
        entry: taplo format --check
        language: system
