[package]
name = "libfuzzer_stb_image_concolic"
version = "0.15.2"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
  "Julius Hohnerlein",
]
edition = "2021"
build = "build.rs"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../../libafl", features = ["concolic_mutation"] }
libafl_bolts = { path = "../../../../libafl_bolts" }
libafl_targets = { path = "../../../../libafl_targets", features = [
  "sancov_pcguard_edges",
  "sancov_cmplog",
  "libfuzzer",
] }
clap = { version = "4.5.18", features = ["derive"] }
log = { version = "0.4.22", features = ["release_max_level_info"] }
mimalloc = { version = "0.1.43", default-features = false }

[build-dependencies]
cc = { version = "1.1.22", features = ["parallel"] }
cmake = "0.1.51"
which = "6.0.3"
symcc_libafl = { path = "../../../../libafl_concolic/symcc_libafl" }
