[package]
name = "qemu_linux_kernel"
version = "0.16.0"
authors = [
  "Romain Malmain <rmalmain@pm.me>",
  "Dongjia Zhang <tokazerkje@outlook.com>",
]
edition = "2021"

[features]
shared = ["libafl_qemu/shared"]

# choose API
lqemu = []
nyx = ["libafl_qemu/nyx", "libvharness_sys/nyx"]

[profile.release]
incremental = true
debug = true
lto = "fat"
codegen-units = 1

[dependencies]
libafl = { path = "../../../crates/libafl" }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
libafl_qemu = { path = "../../../crates/libafl_qemu", default-features = false, features = [
  "x86_64",
  "systemmode",
  #"paranoid_debug"
] }
libafl_targets = { path = "../../../crates/libafl_targets" }
libvharness_sys = { path = "../../../crates/libafl_qemu/libvharness_sys", features = [
  "x86_64",
  "linux-kernel",
] }

env_logger = "0.11.5"
log = "0.4.22"

[build-dependencies]
libafl_qemu_build = { path = "../../../crates/libafl_qemu/libafl_qemu_build" }
