[package]
name = "baby_fuzzer_swap_differential"
version = "0.9.0"
authors = ["Addison Crump <research@addisoncrump.info>"]
edition = "2021"
default-run = "fuzzer_sd"

[features]
tui = []
multimap = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
anyhow = "1"
bindgen = "0.61"
cc = "1.0"

[dependencies]
libafl = { path = "../../libafl" }
libafl_targets = { path = "../../libafl_targets", features = ["sancov_pcguard_hitcounts", "libfuzzer", "sancov_cmplog", "pointer_maps"] }
mimalloc = { version = "*", default-features = false }

libafl_cc = { path = "../../libafl_cc/" }

[[bin]]
name = "fuzzer_sd"
path = "src/main.rs"

[[bin]]
name = "libafl_cc"
path = "src/bin/libafl_cc.rs"
