[package]
name = "frida_executable_fuzzer"
version = "0.13.2"
edition = "2021"

[lib]
name = "frida_executable_fuzzer"
crate_type = ["cdylib"]

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../libafl/", features = [
  "std",
  "llmp_compression",
  "llmp_bind_public",
  "frida_cli",
] } #,  "llmp_small_maps", "llmp_debug"]}
libafl_bolts = { path = "../../../libafl_bolts/" }
frida-gum = { version = "0.13.6", features = [
  "auto-download",
  "event-sink",
  "invocation-listener",
] }
libafl_frida = { path = "../../../libafl_frida", features = ["cmplog"] }
libafl_targets = { path = "../../../libafl_targets", features = [
  "sancov_cmplog",
] }
libc = "0.2"
libloading = "0.7"
num-traits = "0.2"
rangemap = "1.3"
clap = { version = "4.5", features = ["derive"] }
serde = "1.0"
mimalloc = { version = "*", default-features = false }

backtrace = "0.3"
color-backtrace = "0.5"
