[package]
name = "libafl_qemu_build"
version = "0.13.2"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
description = "Builder for LibAFL QEMU"
documentation = "https://docs.rs/libafl_qemu_build"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "./README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "qemu", "instrumentation"]
edition = "2021"
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

[package.metadata.docs.rs]
all-features = true

[features]
shared = []
slirp = []  # build qemu with host libslirp (for user networking)

clippy = [] # special feature for clippy, don't use in normal projectsÂ§

paranoid_debug = [
] # Will perform as many checks as possible. The target will be greatly slowed down.

[dependencies]
bindgen = { version = "0.70.1" }
which = { version = "7.0.0" }
json = "0.12.4"
shell-words = "1.1.0"
pkg-config = "0.3.31"
cc = { version = "1.1.21" }
regex = { version = "1.10.6" }
rustversion = { version = "1.0.17" }
rustc_version = "0.4.1"

[lints]
workspace = true
