[package]
name = "libafl_qemu_build"
version = "0.9.0"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
description = "Builder for LibAFL QEMU"
documentation = "https://docs.rs/libafl_qemu_build"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "./README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "qemu", "instrumentation"]
edition = "2021"
categories = [
    "development-tools::testing",
    "emulators",
    "embedded",
    "os",
    "no-std",
]

[features]
slirp = [] # build qemu with host libslirp (for user networking)

clippy = [] # special feature for clippy, don't use in normal projectsÂ§

[dependencies]
bindgen = "0.63"
cc = "1.0"
which = "4.2"
json = "0.12"
shell-words = "1.1"
pkg-config = "0.3.26"
