[package]
name = "libafl_qemu_build"
version = "0.12.0"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
description = "Builder for LibAFL QEMU"
documentation = "https://docs.rs/libafl_qemu_build"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "./README.md"
license = "MIT OR Apache-2.0"
keywords =["fuzzing", "qemu", "instrumentation"]
edition = "2021"
categories = [
    "development-tools::testing",
    "emulators",
    "embedded",
    "os",
    "no-std",
]

[package.metadata.docs.rs]
all-features = true

[features]
shared = []
slirp = [] # build qemu with host libslirp (for user networking)

clippy = [] # special feature for clippy, don't use in normal projectsÂ§

paranoid_debug = [] # Will perform as many checks as possible. The target will be greatly slowed down.

[dependencies]
bindgen = "0.69.4"
which = "4.4"
json = "0.12"
shell-words = "1.1"
pkg-config = "0.3.26"
cc = "1.0"
regex = "1"
rustversion = "1.0"
rustc_version = "0.4"