[package]
name = "c_code_with_fork_executor"
version = "0.15.2"
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../../libafl" }
libafl_bolts = { path = "../../../../libafl_bolts" }
libc = "0.2.159"
log = { version = "0.4.22", features = ["release_max_level_info"] }

[build-dependencies]
cc = "1.1.21"
