[package]
name = "baby_fuzzer"
version = "0.5.0"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { default-features = false, path = "../../libafl/" }
static-alloc = "0.2.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
cstr_core = "0.2.3"

