[package]
name = "construct_automata"
version = "0.1.0"
edition = "2021"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
description = "LibAFL Gramatron Gramar Construction"
documentation = "https://docs.rs/libafl"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "libafl", "gramatron", "grammar"]
categories = ["development-tools::testing", "emulators", "embedded", "os", "no-std"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
regex = "1"
postcard = "0.7"
lazy_static = "1.4.0"
libafl = { path = "../../../libafl" }
clap = { version = "3.0", features = ["derive"] }
