[package]
name = "libafl_qemu_build"
version.workspace = true
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Romain Malmain <rmalmain@pm.me>",
]
description = "Builder for LibAFL QEMU"
documentation = "https://docs.rs/libafl_qemu_build"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "./README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "qemu", "instrumentation"]
edition = "2024"
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

[package.metadata.docs.rs]
all-features = true

[features]
shared = []
slirp = []  # build qemu with host libslirp (for user networking)

clippy = [] # special feature for clippy, don't use in normal projectsÂ§

qemu_sanitizers = [] # Enable QEMU sanitizers

paranoid_debug = [
] # Will perform as many checks as possible. The target will be greatly slowed down.

[dependencies]
bindgen = { workspace = true }
which = { workspace = true }
json = "0.12.4"
shell-words = "1.1.0"
pkg-config = "0.3.31"
cc = { workspace = true }
regex = { workspace = true }
rustversion = { workspace = true }
rustc_version = "0.4.1"

[lints]
workspace = true
