[package]
name = "libfuzzer_windows_asan"
version = "0.15.2"
authors = ["Max Ammann <max@maxammann.org>"]
edition = "2021"
categories = ["development-tools::testing"]

[features]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../libafl" }
libafl_bolts = { path = "../../../libafl_bolts" }
libafl_targets = { path = "../../../libafl_targets", features = [
  "libfuzzer",
  "sancov_pcguard_edges",
] }
libafl_cc = { path = "../../../libafl_cc" }
log = { version = "0.4.22", features = ["release_max_level_info"] }

[build-dependencies]
cc = { version = "1.1.21" }

[lib]
name = "libfuzzer_windows_asan"
crate-type = ["staticlib"]
