[package]
name = "baby_fuzzer_multi"
version = "0.15.2"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
  "Addison Crump <me@addisoncrump.info>",
]
edition = "2021"

[features]
default = ["std"]
tui = ["libafl/tui_monitor"]
std = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../libafl", features = ["multipart_inputs"] }
libafl_bolts = { path = "../../../libafl_bolts" }
log = { version = "0.4.22", features = ["release_max_level_info"] }
