[package]
name = "desyscall"
version = "0.15.2"
edition = "2024"
description = "DeSyscall: Hooks syscalls for reduces overhead during in-process fuzzing"
repository = "https://github.com/AFLplusplus/LibAFL/"
license = "MIT OR Apache-2.0"
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]
keywords = ["fuzzing", "libafl", "ldpreload"]

[dependencies]
meminterval = "0.4"
libc = "0.2"

[dev-dependencies]
rusty-fork = "0.3.0"

[build-dependencies]
cc = "1"

[lib]
name = "desyscall"
crate-type = ["rlib", "cdylib"]
