[package]
name = "baby_fuzzer_wasm"
version = "0.15.2"
authors = ["Addison Crump <research@addisoncrump.info>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
js-sys = "0.3.70"
log = { version = "0.4.22", features = ["release_max_level_info"] }
wasm-bindgen = "0.2.93"

libafl = { path = "../../../libafl", default-features = false }
libafl_bolts = { path = "../../../libafl_bolts", default-features = false }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

web-sys = { version = "0.3.70", features = [
  'console',
  'Window',
  'Performance',
  'PerformanceTiming',
] }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
