[package]
name = "dynamic_analysis"
version = "0.14.1"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
std = []
no_link_main = ["libafl_targets/libfuzzer_no_link_main"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.release-fuzzbench]
inherits = "release"
debug = false
strip = true

[build-dependencies]
cc = { version = "1.1.21", features = ["parallel"] }
which = "6.0.3"

[dependencies]
env_logger = "0.11.5"
once_cell = "1.19.0"
libafl = { path = "../../../libafl" }
libafl_bolts = { path = "../../../libafl_bolts" }
libafl_targets = { path = "../../../libafl_targets", features = [
  "sancov_pcguard_hitcounts",
  "sancov_cmplog",
  "libfuzzer",
  "function-logging",
] }
# TODO Include it only when building cc
libafl_cc = { path = "../../../libafl_cc" }

clap = { version = "4.5.18", features = ["default"] }
log = { version = "0.4.22", features = ["release_max_level_info"] }
nix = { version = "0.29.0", features = ["fs"] }
mimalloc = { version = "0.1.43", default-features = false }

[lib]
name = "fuzzbench"
crate-type = ["staticlib"]
