[package]
name = "libnoaslr"
version = "0.1.0"
edition = "2021"

[lib]
name = "noaslr"
path = "src/lib.rs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", default-features = false }
ctor = { version = "0.2", default-features = false }
nix = { version = "0.27", default-features = false, features = ["process", "personality"] }

[target.'cfg(any(target_os = "freebsd", target_os = "netbsd"))'.dependencies]
libc = "0.2" 
