[package]
name = "baby_fuzzer_swap_differential"
version = "0.15.2"
authors = ["Addison Crump <research@addisoncrump.info>"]
edition = "2021"
default-run = "fuzzer_sd"

[features]
tui = ["libafl/tui_monitor"]
multimap = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
anyhow = "1.0.89"
bindgen = "0.71.1"
cc = "=1.2.7"      # fix me later

[dependencies]
libafl = { path = "../../../libafl", features = ["tui_monitor"] }
libafl_bolts = { path = "../../../libafl_bolts" }
libafl_targets = { path = "../../../libafl_targets", features = [
  "sancov_pcguard_hitcounts",
  "libfuzzer",
  "sancov_cmplog",
  "pointer_maps",
] }
log = { version = "0.4.22", features = ["release_max_level_info"] }
mimalloc = { version = "0.1.43", default-features = false }

libafl_cc = { path = "../../../libafl_cc" }

[[bin]]
name = "fuzzer_sd"
path = "src/main.rs"

[[bin]]
name = "libafl_cc"
path = "src/bin/libafl_cc.rs"
