[package]
name = "drcov_utils"
edition = "2024"
version.workspace = true
description = "Utility functions to work with DrCov coverage files"
repository = "https://github.com/AFLplusplus/LibAFL/"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]
keywords = ["fuzzing", "libafl", "drcov"]

[dependencies]
env_logger = "0.11.6"
libafl_targets = { workspace = true, default-features = true }
clap = { workspace = true, features = ["derive", "wrap_help"] }
walkdir = "2.5"

[lints]
workspace = true
