[package]
name = "tutorial"
version = "0.15.2"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.1.21", features = ["parallel"] }
which = "6.0.3"

[dependencies]
libafl = { path = "../../../libafl", features = ["default", "rand_trait"] }
libafl_bolts = { path = "../../../libafl_bolts" }
libafl_targets = { path = "../../../libafl_targets", features = [
  "sancov_pcguard_hitcounts",
  "libfuzzer",
  "sancov_cmplog",
] }
serde = { version = "1.0.210", default-features = false, features = [
  "alloc",
] } # serialization lib
lain = { version = "0.5.6", features = [
  "serde_support",
], git = "https://github.com/AFLplusplus/lain.git", rev = "6ac90a35cfff15e314cf33b098f6cac4691c7ab3" } # We're using a lain fork compatible with libafl's rand version
# TODO Include it only when building cc
libafl_cc = { path = "../../../libafl_cc" }
log = { version = "0.4.22", features = ["release_max_level_info"] }

[lib]
name = "tutorial"
crate-type = ["staticlib"]
