[package]
name = "libafl_repo_tools"
version = "0.15.2"
edition = "2024"
description = "A set of useful tools to manage the LibAFL repository"
authors = ["Romain Malmain <romain.malmain@pm.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AFLplusplus/LibAFL.git"

[dependencies]
project-root = "0.2"
walkdir = "2.5"
regex = "1.10"
tokio = { version = "1.38", features = [
  "process",
  "rt",
  "rt-multi-thread",
  "macros",
] }
clap = { version = "4.5", features = ["derive"] }
exitcode = "1.1"
which = "7.0.2"
colored = "3.0.0"
