[package]
name = "nyx_libxml2_standalone"
version = "0.9.0"
edition = "2021"
default-run = "nyx_libxml2_standalone"

[dependencies]
libafl = { path = "../../libafl" }
libafl_cc = { path = "../../libafl_cc" }
libafl_nyx = { path = "../../libafl_nyx" }

[profile.release]
codegen-units = 1
opt-level = 3
