[package]
name = "fuzzbench_qemu"
version = "0.16.0"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.release-fuzzbench]
inherits = "release"
debug = false
strip = true

[dependencies]
libafl = { path = "../../../crates/libafl" }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
libafl_qemu = { path = "../../../crates/libafl_qemu", features = [
  "x86_64",
  "usermode",
] }
libafl_targets = { path = "../../../crates/libafl_targets", version = "0.16.0" }

env_logger = "0.11.5"
log = { version = "0.4.22", features = ["release_max_level_info"] }
clap = { version = "4.5.18", features = ["default"] }
mimalloc = "0.1.48"
scudo = "0.1.3"
