name: Setup Rust Environment
description: Sets up the Rust environment for the CI workflow
runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Windows Build
      shell: pwsh
      run: cargo build --verbose
    - name: Build docs
      shell: pwsh
      run: cargo doc
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set LIBCLANG_PATH
      shell: pwsh
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
    - name: install cargo-make
      shell: pwsh
      run: cargo install --force cargo-make