[package]
name = "libafl_libfuzzer_runtime"
version = "0.11.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["fork"]
## Enables forking mode for the LibAFL launcher (instead of starting new processes)
fork = ["libafl/fork"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

# debug-free release profile for fuzzbench due to space restrictions
[profile.release-fuzzbench]
inherits = "release"
debug = false
strip = true


[lib]
name = "afl_libfuzzer_runtime" # TODO fix name once cargo-fuzz stops stripping double-prefixes
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
libafl = { path = "../../libafl", default-features = false, features = ["std", "derive", "llmp_compression", "rand_trait", "regex", "errors_backtrace", "serdeany_autoreg", "tui_monitor", "unicode"] }
libafl_bolts = { path = "../../libafl_bolts", default-features = false, features = ["std", "derive", "llmp_compression", "rand_trait", "serdeany_autoreg", "errors_backtrace"] }
libafl_targets = { path = "../../libafl_targets", features = ["sancov_8bit", "sancov_cmplog", "libfuzzer", "libfuzzer_oom", "libfuzzer_define_run_driver", "libfuzzer_interceptors", "sanitizers_flags", "whole_archive"] }

ahash = { version = "0.8.3", default-features = false }
libc = "0.2.139"
log = "0.4.17"
mimalloc = { version = "0.1.34", default-features = false }
num-traits = "0.2.15"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] } # serialization lib

# clippy-suggested optimised byte counter
bytecount = "0.6.3"

# for identifying if we can grimoire-ify
utf8-chars = "3.0.1"

env_logger = "0.10"

[build-dependencies]
bindgen = "0.68.1"
cc = { version = "1.0", features = ["parallel"] }

[workspace]
