[package]
name = "tutorial"
version = "0.7.1"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
which = { version = "4.0.2" }
num_cpus = "1.0"

[dependencies]
libafl = { path = "../../libafl/", features = ["default", "rand_trait"] }
libafl_derive = { path = "../../libafl_derive/" }
libafl_targets = { path = "../../libafl_targets/", features = ["sancov_pcguard_hitcounts", "libfuzzer", "sancov_cmplog"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] } # serialization lib
lain = { version = "0.5", features = ["serde_support"]}
# TODO Include it only when building cc
libafl_cc = { path = "../../libafl_cc/" }

[lib]
name = "tutorial"
crate-type = ["staticlib"]
