[package]
name = "libfuzzer_stb_image_sugar"
version = "0.15.3"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = { path = "../../../crates/libafl" }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
libafl_targets = { path = "../../../crates/libafl_targets", features = [
  "sancov_pcguard_edges",
  "sancov_cmplog",
  "libfuzzer",
] }
libafl_sugar = { path = "../../../crates/libafl_sugar" }
log = { version = "0.4.22", features = ["release_max_level_info"] }
mimalloc = { version = "0.1.43", default-features = false }
libafl_cc = { path = "../../../crates/libafl_cc" }

[build-dependencies]
cc = { version = "1.1.21", features = ["parallel"] }

[lib]
name = "libfuzzer_stb_image_sugar"
crate-type = ["staticlib"]
