[package]
name = "libfuzzer_libpng_launcher_centralized_multi_machine"
version = "0.15.2"
authors = [
  "Romain Malmain <romain.malmain@pm.me>",
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.1.21", features = ["parallel"] }
which = "6.0.3"

[dependencies]
# no llmp compression for now, better perfs.
libafl = { path = "../../../libafl", default-features = false, features = [
  "std",
  "derive",
  "llmp_small_maps",
  "llmp_broker_timeouts",
  "rand_trait",
  "fork",
  "prelude",
  "gzip",
  "regex",
  "serdeany_autoreg",
  "tui_monitor",
  "std",
  "derive",
  "rand_trait",
  "fork",
  "prelude",
  "gzip",
  "regex",
  "multi_machine",
  "errors_backtrace",
] }
libafl_bolts = { path = "../../../libafl_bolts", features = ["xxh3"] }
libafl_targets = { path = "../../../libafl_targets", features = [
  "sancov_pcguard_hitcounts",
  "libfuzzer",
] }
# TODO Include it only when building cc
libafl_cc = { path = "../../../libafl_cc" }

clap = { version = "4.5.18", features = ["derive"] }
log = { version = "0.4.22", features = ["release_max_level_info"] }
mimalloc = { version = "0.1.43", default-features = false }
env_logger = "0.11.5"

[lib]
name = "libfuzzer_libpng"
crate-type = ["staticlib"]
