[package]
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
name = "libafl_benches"
version.workspace = true
edition = "2021"
description = "LibAFL Benchmarks"
documentation = "https://docs.rs/libafl"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "libafl", "benchmarks"]
categories = ["development-tools::testing", "emulators", "embedded", "os", "no-std"]

[dev-dependencies]
criterion = "0.5" # Benchmarking
ahash = { version = "0.8", default-features=false } # The hash function already used in hashbrown
rustc-hash = { version = "1.1", default-features=false } # yet another hash
xxhash-rust = { version = "0.8.5", features = ["xxh3"] } # xxh3 hashing for rust
libafl_bolts = { path = "../../libafl_bolts", default-features=false, features = ["xxh3", "alloc"] } # libafl_bolts

[[bench]]
name = "rand_speeds"
harness = false

[[bench]]
name = "hash_speeds"
harness = false

