[package]
name = "multi_machine_generator"
authors = ["Romain Malmain <romain.malmain@pm.me>"]
version = "0.15.2"
description = "Generator for multi-machine setup"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "testing", "security"]
edition = "2024"

[dependencies]
petgraph = "0.6"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
